
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.Notebook ServersNotebook;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Label label7;

	private global::Gtk.Entry usernameEntry;

	private global::Gtk.Label label8;

	private global::Gtk.Entry serverEntry;

	private global::Gtk.Button button1;

	private global::Gtk.Label label3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.ServersNotebook = new global::Gtk.Notebook();
		this.ServersNotebook.CanFocus = true;
		this.ServersNotebook.Name = "ServersNotebook";
		this.ServersNotebook.CurrentPage = 0;
		this.ServersNotebook.Scrollable = true;
		// Container child ServersNotebook.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Enter your desired username:");
		this.vbox3.Add(this.label7);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label7]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.usernameEntry = new global::Gtk.Entry();
		this.usernameEntry.CanFocus = true;
		this.usernameEntry.Name = "usernameEntry";
		this.usernameEntry.Text = global::Mono.Unix.Catalog.GetString("Muny");
		this.usernameEntry.IsEditable = true;
		this.usernameEntry.InvisibleChar = '●';
		this.vbox3.Add(this.usernameEntry);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.usernameEntry]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Enter server address <i><b>ex:</b> 127.0.0.1[:1337]</i>");
		this.label8.UseMarkup = true;
		this.vbox3.Add(this.label8);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label8]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.serverEntry = new global::Gtk.Entry();
		this.serverEntry.CanFocus = true;
		this.serverEntry.Name = "serverEntry";
		this.serverEntry.Text = global::Mono.Unix.Catalog.GetString("198.74.49.203:6789");
		this.serverEntry.IsEditable = true;
		this.serverEntry.InvisibleChar = '●';
		this.vbox3.Add(this.serverEntry);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.serverEntry]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Connect to server");
		this.vbox3.Add(this.button1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button1]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		this.ServersNotebook.Add(this.vbox3);
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Join Server");
		this.ServersNotebook.SetTabLabel(this.vbox3, this.label3);
		this.label3.ShowAll();
		w1.Add(this.ServersNotebook);
		this.GtkScrolledWindow.Add(w1);
		this.Add(this.GtkScrolledWindow);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 471;
		this.DefaultHeight = 352;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ServersNotebook.SwitchPage += new global::Gtk.SwitchPageHandler(this.ServersNotebook_SwitchPage);
		this.button1.Clicked += new global::System.EventHandler(this.ConnectButton_Click);
	}
}
